ignore_merge_commits = true
post_bump_hooks = [
  "git push",
  "git push origin {{version}}",
]
pre_bump_hooks = [
  "just check",
]

[changelog]
owner = "kleinweb"
path = "CHANGELOG.md"
remote = "github.com"
repository = "php-coding-standards"
template = "remote"
